# Generated by Django 4.2.3 on 2023-08-30 08:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorythree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorytwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(default=0, help_text='درصد تخفیف')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='نام محصول:', max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default='1000', help_text='قیمت محصول: ', null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت جدید (همراه با تخفیف )')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='  واحد محاصبه:', max_length=200, null=True)),
                ('Lowest_wholesale_amount', models.CharField(blank=True, help_text='پایین ترین مقدار برای خرید:', max_length=200, null=True)),
                ('discribtion', models.CharField(blank=True, help_text='توضیحات محصول:', max_length=1000, null=True)),
                ('introduction', models.CharField(blank=True, help_text='معرفی بیشتر محصول:', max_length=2000, null=True)),
                ('Alloy', models.CharField(blank=True, help_text='آلیاژ یا جنس محصول:', max_length=200, null=True)),
                ('warranty', models.IntegerField(blank=True, help_text='گارانتی محصول:', null=True)),
                ('made_in', models.CharField(blank=True, help_text='کشور سازنده محصول:', max_length=50, null=True)),
                ('dimensions', models.FloatField(blank=True, help_text='مقدار اولیه ابعاد :', null=True)),
                ('in_dimensions', models.FloatField(blank=True, help_text='مقدار دوم ابعاد', null=True)),
                ('Weight', models.IntegerField(blank=True, help_text='وزن محصول:', null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار موجودی ')),
                ('slug', models.SlugField(blank=True, help_text='شماره جهت فیلتر (کد محصول ):', max_length=255, null=True, unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='assets\\img\\poducts')),
                ('color1', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color2', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color3', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color4', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color5', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color6', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color7', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color8', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color9', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('color10', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None)),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='product.categorytwo', verbose_name='دسته بندی 2')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='product.categorythree', verbose_name='دسته بندی 3')),
                ('kingcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kingcategory', to='product.kingcategory', verbose_name='دسته بندی اصلی ')),
                ('special_offers', models.ManyToManyField(blank=True, related_name='SpecialOffer', to='product.specialoffer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(through='product.OrderItem', to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='Customer_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='عنوان نظر', max_length=2000, null=True)),
                ('score', models.FloatField(blank=True, default=100, null=True)),
                ('positive_points', models.CharField(blank=True, help_text='نکات مثبت', max_length=2000, null=True)),
                ('cons', models.CharField(blank=True, help_text='نکات منفی ', max_length=2000, null=True)),
                ('comment', models.TextField(help_text=' متن نظر')),
                ('like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='product.product', verbose_name='محصول مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='categorytwo',
            name='grouping2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catg', to='product.kingcategory', verbose_name='دسته بندی 2'),
        ),
        migrations.AddField(
            model_name='categorythree',
            name='grouping3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat3', to='product.categorytwo', verbose_name='grouping2'),
        ),
        migrations.CreateModel(
            name='Bestselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='از تاریخ')),
                ('up_to_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestselling', to='product.product', verbose_name='محصول پرفروش ')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='عنوان فیلد', max_length=2000, null=True)),
                ('content', models.CharField(blank=True, help_text='محتوا ی فیلد', max_length=2000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='product.product', verbose_name='field')),
            ],
        ),
    ]
