# Generated by Django 4.2.3 on 2023-08-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_offers',
        ),
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SpecialOffer', to='product.specialoffer'),
            preserve_default=False,
        ),
    ]
