# Generated by Django 4.2.3 on 2023-08-31 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_special_offers_product_special_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_offers',
        ),
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
    ]
