# Generated by Django 4.2.3 on 2023-09-03 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ('-created',), 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(default=1, editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(default=1, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
