# Generated by Django 4.2.3 on 2023-09-03 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_apikey_api_name_apikey_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={},
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='created',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='hashed_key',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='revoked',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
